<a href="https://colab.research.google.com/github/wootaehyeon/pytorch-Tutorial/blob/main/intro_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import torch
import numpy as np

In [7]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [8]:
#Addition
tensor_a +tensor_b

tensor([ 6,  8, 10, 12])

In [10]:
#Addition Longhand
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [13]:
#subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [12]:
#subfuntion
torch.sub(tensor_a,tensor_b)

tensor([-4, -4, -4, -4])

Multiplication